# https://aka.ms/yaml

name: "$(date:yyyyMMdd)$(rev:.r)"

trigger:
  - main

pr:
  - main

jobs:
  - job: Build
    strategy:
      matrix:
        Debug:
          configuration: Debug
          Codeql.Enabled: true
          Codeql.BuildIdentifier: PerfView
        Release:
          configuration: Release
    pool:
      vmImage: 'windows-2022'
      name: Azure Pipelines
      demands:
      - msbuild
      - vstest

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 3.1'
      inputs:
        version: 3.1.x

    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet.exe'
      inputs:
        versionSpec: 6.3.0

    - task: NuGetCommand@2
      displayName: 'NuGet Restore PerfView.sln'
      inputs:
        restoreSolution: PerfView.sln
        feedsToUse: config
        includeNuGetOrg: false
        nugetConfigPath: '.\NuGet.config'

    - task: MSBuild@1
      displayName: 'Build PerfView.sln'
      inputs:
        solution: PerfView.sln
        configuration: $(configuration)

    - task: VSTest@2
      displayName: Test
      inputs:
        testRunTitle: 'LinuxTracing ($(configuration))'
        failOnMinTestsNotRun: true
        testAssemblyVer2: '**\bin\$(configuration)\**\Tests.dll'

    - task: VSTest@2
      displayName: Test LinuxTracing
      inputs:
        testRunTitle: LinuxTracing ($(configuration))
        failOnMinTestsNotRun: true
        testAssemblyVer2: '**\bin\$(configuration)\**\LinuxTracing.Tests.dll'

    - task: VSTest@2
      displayName: Test TraceEvent
      inputs:
        testRunTitle: TraceEvent ($(configuration))
        failOnMinTestsNotRun: true
        testAssemblyVer2: '**\bin\$(configuration)\**\TraceEventTests.dll'

    - task: VSTest@2
      displayName: Test PerfView
      inputs:
        testRunTitle: PerfView ($(configuration))
        failOnMinTestsNotRun: true
        testAssemblyVer2: '**\bin\$(configuration)\**\PerfViewTests.dll'

    - task: CopyFiles@2
      displayName: 'Copy Files to Artifacts Staging'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**\bin\$(BuildConfiguration)\**'
        TargetFolder: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'PerfViewBinaries-$(configuration)'
      condition: succeededOrFailed()

  - job: PerfCollect
    pool:
      vmImage: 'ubuntu-latest'
      name: Azure Pipelines

    steps:
    - task: DockerInstaller@0
      displayName: 'Install Docker'

    - task: Bash@3
      displayName: 'Build Containers'
      inputs:
        targetType: filePath
        filePath: './src/perfcollect/tests/build-containers.sh'
        workingDirectory: src/perfcollect/tests

    - task: Bash@3
      displayName: 'Run Tests'
      inputs:
        targetType: filePath
        filePath: './src/perfcollect/tests/run-containers.sh'
        workingDirectory: src/perfcollect/tests

